title: "Nhat An Trinh"
author: "Nhat An Trinh"
description: "Copyright 2022 Nhat An Trinh."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "README.md", title: "Research", icon: adress-card}
  - {file: "natrinh.pdf", title: "CV", icon:CV}  
  - {file: "README.md", title: "Contact", icon: adress-card}  
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:nhatan.trinh@hu-berlin.de"}
  - {title: Github, icon: github, url: "https://github.com/NATrinh"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
