title: "Nhat An Trinh"
author: "Nhat An Trinh"
description: "© 2022 Nhat An Trinh." # Made with Jekyll using the {title: contrast, url: "https://github.com/niklasbuschmann/contrast"} theme.
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "README.md", title: "Projects"}
  - {file: "README.md", title: "Publications"}
  - {url: "/CV_natrinh.pdf", title: CV}  
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Twitter, icon: twitter, url: "https://twitter.com/nhatantrinh"}
  - {title: Google Scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=9nAOOBoAAAAJ&hl=en"}
  - {title: Mail, icon: envelope, url: "mailto:nhatan.trinh@hu-berlin.de"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
